# -*- coding: utf-8 -*-
"""aula4_ads2ma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AO12T7RT4VXBtZ6zWU6eoOMrs8ckBTq8
"""

# INSTITUIÇÃO: UNINASSAU
# DOCENTE: CLOVES ROCHA
# ESTUDANTE: FULANO DE TAL
# Tipos Primitivos de Dados - Guia Aprender Python

#print('Cloves nota 10')
#c = 10
#print(c,'é um dado do tipo: ')
#print(type(c))

# 3. Operadores Aritméticos - Guia Aprender Python
# 10 + 9 adição
# 9 - 8 subtração
# 9 * 7 multiplicação
# 10 / 3 divisão
# 5 ** 3 exponenciação
# 10 // 3  divisão inteira
# 10 % 3 resto da divisão
c = 2**3
print(c, 'resultado da exponenciação.')
c = 2//3
print(c, 'resultado da divisão inteira.')
c = 10%3
print(c, 'resultado da divisão inteira.')

# 4. Operadores Relacionais Simples.
# 11 > 10
# 9 < 8
a = 1
b = 1
a == b